version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  django-app:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://admin:admin123@mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongo_data:

