name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image and create container
        run: |
          docker build -t ankitpheaptrace/user-management-api .
          docker push ankitpheaptrace/user-management-api
      
      - name: Run Docker Container (for test/demo)
        run: |
          docker run -d --name user-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/user-management-api:latest
          sleep 10 
          docker ps 
